<? use MPF\Text; use MPF\ENV; ?><!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <title>MPF</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="description" content="Environment control for MPF"/>
    <style type="text/css">
    </style>
</head>
<body><? if (array_key_exists('clearAllCache', $_GET)): ?>

<ul>
<? while ($info = ENV::clearAllCache()): ?>
    <li><strong><?= $info['title'] ?></strong>: <i><?= $info['outcome'] ?></i></li>
<? endwhile; ?>
</ul>

<? else: echo Text::byXml('environment')->get('intro'); endif; ?>
</body>
</html>