<?
    if (\MPF\User::bySession()) {
        header('Location: /');
        exit;
    }

    $GLOBALS['cssFiles'] = array('/media/css/login.css');
    $loginText = \MPF\Text::byXml('mpf_login');
    $totalUsers = \MPF\User::getTotalEntries();

?>
<form name="login" action="/rest/login.html" method="PUT">
    <fieldset>
        <legend><?= $loginText->get('title') ?></legend>
        <? if ($totalUsers == 1): ?><p class="information"><?= $loginText->get('firstUser') ?></p><? endif; ?>
        <div><label for="username"><?= $loginText->get('username') ?></label><input type="text" name="username" id="username" tabindex="1" /></div>
        <div>
            <label for="password"><?= $loginText->get('password') ?></label>
            <input type="password" name="password" id="password" tabindex="2" />
        </div>
        <div class="newUser">
            <label><?= $loginText->get('passwordStrength') ?></label>
            <div data-mpf-password-strength="password"><div data-mpf-password-strength-meter="password" class="mpfStrengthLow">&nbsp;</div></div>
            <div data-mpf-tooltip="passwordStrength">
                <label><img src="media/images/icons/16x16/information.png" width="16" height="16" alt="i" /></label>
                <section>
                    <h5><?= $loginText->get('passwordStrengthTitle') ?></h5>
                    <hr />
                    <?= $loginText->get('passwordStrengthDescription') ?>
                </section>
            </div>
        </div>
        <div class="newUser"><label for="passwordConfirm"><?= $loginText->get('passwordConfirm') ?></label><input type="password" name="passwordConfirm" id="passwordConfirm" tabindex="3" /></div>
        <? if ($totalUsers != 1): ?><p class="existingUser"><?= $loginText->get('passwordLost') ?></p><? endif; ?>
        <div><label for="new"><?= $loginText->get('newUser') ?></label><input type="checkbox" name="new" id="new" <? if ($totalUsers == 1): ?>checked="checked" disabled="disabled" <? endif; ?> /></div>
        <input type="submit" value="<?= $loginText->get('submit') ?>" class="gradientGreen" tabindex="4" />
    </fieldset>
</form>
<script type="text/javascript">
$(document).ready(function () {
    "use strict";
    var $loginForm = $('form[name="login"]');

    $('#new').click(function () {
        $('.newUser').slideUp();

        if (this.checked) {
            $('.existingUser').slideUp(function () {
                $('.newUser').slideDown();
            });
            $('#passwordConfirm').validate('required passwordConfirm');
            $('#password').validate('required passwordStrength password', 'keyup');
        } else {
            $('.newUser').slideUp(function () {
                $('.existingUser').slideDown();
            });
            $('#passwordConfirm').unvalidate();
            $('#password').unvalidate();
            $('#password').validate('required password');
        }
    });

    $('#new:checked').each(function (index, element) {
       $('.newUser').slideDown();
       $('#passwordConfirm').validate('required passwordConfirm');
       $('#password').validate('required passwordStrength password', 'keyup');
    });

    $('#username').focus();
    $('#username').validate('required username');
    $('#password').validate('required password');
    $loginForm.submit(function () {
        $('[data-form-error-img]').remove();

        $loginForm.prop('action', mpf.restUrl+'user/'+$('#username').val()+'/login');
        if ($('#new:checked').length === 1) {
            $loginForm.prop('action', mpf.restUrl+'user/');
            $loginForm.prop('method', 'post');
        }

        $loginForm.validate(function (isValid, invalidFields) {
            if (!isValid) {
                $loginForm.addErrors(invalidFields);
                return;
            }

            $loginForm.ajaxSubmit(function (errors, response) {
                if (errors) {
                    $loginForm.addErrors(errors);
                    return;
                }

                document.location.href = "/mpf-admin/";
            });
        });

        return false;
    });
});
</script>